name=elysflowers
description=more flowers
optional_depends=default,flowerpot,mcl_flowerpot,mcl_flowers,mcl_biomes,mcl_levelgen,mcl_vars,mcl_core,ebiomes,ethereal,naturalbiomes,prairie,asuna_core,dorwinion
supported_games = minetest_game,mineclonia,mesecraft, dreambuilder_game,asuna
title=Elysflowers
release = 38550
author = erey23
